"""Finalization and package-validation helpers for score experiments."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import solve_dns_homework as solver
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from . import solve_dns_homework as solver

try:
    from score_exp_config import (
        DNS1_LOCKED_SHA256,
        DNS2_LOCKED_SHA256,
        DNS3_INTERPRETABLE_ALGORITHM_ORDER,
        DNS3_INTERPRETABLE_EVIDENCE_DIR,
        DNS3_INTERPRETABLE_FALLBACK_SHA256,
        DNS3_INTERPRETABLE_MAX_CLUSTER_FRACTION,
        DNS3_INTERPRETABLE_MIN_ARI,
        DNS3_INTERPRETABLE_MIN_NMI,
        DNS3_INTERPRETABLE_MIN_SEPARATION_RATIO,
        DNS3_INTERPRETABLE_PROFILE_SCORE_FORMULA,
        DNS3_INTERPRETABLE_ROUTE_ORDER,
        DNS3_INTERPRETABLE_SEED_SET,
        EVIDENCE_DIR,
    )
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from .score_exp_config import (
        DNS1_LOCKED_SHA256,
        DNS2_LOCKED_SHA256,
        DNS3_INTERPRETABLE_ALGORITHM_ORDER,
        DNS3_INTERPRETABLE_EVIDENCE_DIR,
        DNS3_INTERPRETABLE_FALLBACK_SHA256,
        DNS3_INTERPRETABLE_MAX_CLUSTER_FRACTION,
        DNS3_INTERPRETABLE_MIN_ARI,
        DNS3_INTERPRETABLE_MIN_NMI,
        DNS3_INTERPRETABLE_MIN_SEPARATION_RATIO,
        DNS3_INTERPRETABLE_PROFILE_SCORE_FORMULA,
        DNS3_INTERPRETABLE_ROUTE_ORDER,
        DNS3_INTERPRETABLE_SEED_SET,
        EVIDENCE_DIR,
    )

try:
    from score_exp_common import (
        _safe_float,
        _safe_int,
        _unique_reasons,
        copy_label_if_needed,
        expected_sha_from_hashes,
        hash_file,
        project_path,
        project_relative,
        read_json,
        read_label_csv,
        write_json,
    )
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from .score_exp_common import (
        _safe_float,
        _safe_int,
        _unique_reasons,
        copy_label_if_needed,
        expected_sha_from_hashes,
        hash_file,
        project_path,
        project_relative,
        read_json,
        read_label_csv,
        write_json,
    )

try:
    from score_exp_artifacts import compact_counts, existing_source_with_hash, find_variant_candidate, validation_status
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from .score_exp_artifacts import compact_counts, existing_source_with_hash, find_variant_candidate, validation_status

try:
    from score_exp_dns3_core import dns3_label_diagnostics
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from .score_exp_dns3_core import dns3_label_diagnostics

try:
    from score_exp_dns3_interpretable import dns3_interpretable_label_integrity, dns3_interpretable_thresholds
except ModuleNotFoundError:  # Allows package-style imports from the project root.
    from .score_exp_dns3_interpretable import dns3_interpretable_label_integrity, dns3_interpretable_thresholds


def write_task7_run_summary(final_payload: dict[str, Any]) -> None:
    decisions = final_payload["decisions"]
    dns1 = decisions["dns1"]
    dns2 = decisions["dns2"]
    dns3 = decisions["dns3"]
    dns1_metrics = dns1["metrics"]
    dns3_baseline = dns3["baseline_proxy"]
    dns3_primary = dns3["primary_proxy"]
    lines = [
        "# DNS Homework Solver Run Summary",
        "",
        "Generated by Task 7 final selection from existing Task 4/5/6 evidence; no new model grid was run.",
        "",
        "## Final deterministic selection",
        "- Rule: dns2 baseline unless Task 6 explicitly selected otherwise; dns3 primary only if gates pass and proxy beats baseline; dns1 primary only if gates pass and proxy beats baseline comparator.",
        f"- dns1: {dns1['selection_name']} / {dns1['variant']} from run {dns1['run_id']} ({dns1['reason']}).",
        f"- dns2: {dns2['selection_name']} from Task 6 freeze evidence; sha256={dns2['sha256']}.",
        f"- dns3: {dns3['selection_name']} from run {dns3['run_id']} ({dns3['reason']}).",
        "",
        "## dns1",
        f"- Selected rows: {dns1_metrics.get('row_count')} (known={dns1_metrics.get('known_count')}, extra={dns1_metrics.get('extra_count')})",
        f"- Proxy: selected={dns1.get('proxy_score')} baseline_comparator={dns1.get('baseline_proxy_score')}",
        f"- Family macro-F1 CV: {dns1_metrics.get('family_oof_score')}",
        f"- Extra risk mean/min: {dns1_metrics.get('selected_extra_risk_mean')}/{dns1_metrics.get('selected_extra_risk_min')}",
        f"- Family margin mean/min: {dns1_metrics.get('family_margin_mean')}/{dns1_metrics.get('family_margin_min')}",
        f"- Largest family fraction: {dns1_metrics.get('largest_family_fraction')}",
        f"- Selected extra family counts: {compact_counts(dns1_metrics.get('selected_extra_family_counts'))}",
        "",
        "## dns2",
        f"- Rows predicted: {dns2.get('row_count')}",
        f"- Label counts: {compact_counts(dns2.get('label_counts'))}",
        f"- Positive rate: {dns2.get('positive_rate')}",
        f"- Frozen baseline hash: {dns2.get('sha256')}",
        "",
        "## dns3",
        f"- Decision: {dns3['selection_name']} because {dns3['reason']}",
        f"- Baseline proxy: {dns3_baseline.get('proxy_score')} (clusters={dns3_baseline.get('cluster_count')}, max_cluster_fraction={dns3_baseline.get('max_cluster_fraction')}, min_cluster_size={dns3_baseline.get('min_cluster_size')}, entropy={dns3_baseline.get('cluster_entropy_normalized')}, median_nmi={dns3_baseline.get('median_pairwise_nmi_across_seeds')})",
        f"- Primary candidate proxy: {dns3_primary.get('proxy_score')} (variant={dns3.get('primary_variant')}, gate_accepted={dns3.get('primary_gate_accepted')})",
        f"- Final cluster counts: {compact_counts(dns3.get('selected_label_counts'))}",
        "",
        "## Final artifacts",
        "- results/dns1/label.csv",
        "- results/dns2/label.csv",
        "- results/dns3/label.csv",
        "- submission/answers/dns1.csv",
        "- submission/answers/dns2.csv",
        "- submission/answers/dns3.csv",
    ]
    path = solver.REPORTS_DIR / "run_summary.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_task7_finalize(args: argparse.Namespace) -> dict[str, Any]:
    if args.task != "all":
        raise ValueError("Task 7 finalize must be run with --task all")

    dns1_manifest_path = EVIDENCE_DIR / "dns1_candidate_selection.json"
    dns3_manifest_path = EVIDENCE_DIR / "dns3_candidate_selection.json"
    dns2_freeze_path = EVIDENCE_DIR / "task-6-dns2-freeze.json"
    dns1_manifest = read_json(dns1_manifest_path)
    dns3_manifest = read_json(dns3_manifest_path)
    dns2_freeze = read_json(dns2_freeze_path)

    dns1_selection = dns1_manifest.get("selection", {})
    dns1_selected = dns1_selection.get("selected", {})
    dns1_rules = dns1_selection.get("rules", {})
    dns1_selected_variant = str(dns1_selected.get("variant"))
    dns1_candidate = find_variant_candidate(dns1_manifest, dns1_selected_variant)
    dns1_candidate_gate = dns1_candidate.get("gate", {})
    dns1_baseline_proxy_score = float(dns1_rules.get("baseline_proxy_score", dns1_manifest.get("baseline_proxy", {}).get("proxy_score", 0.0)))
    dns1_selected_proxy_score = float(dns1_selected.get("proxy_score", 0.0))
    dns1_use_primary = bool(
        dns1_selection.get("selection_name") == "dns1_primary"
        and dns1_candidate_gate.get("accepted")
        and dns1_rules.get("proxy_improves_over_baseline")
        and dns1_selected_proxy_score > dns1_baseline_proxy_score
    )
    if dns1_use_primary:
        dns1_source_rel = str(dns1_selected["dns1_label_path"])
        dns1_expected_sha = expected_sha_from_hashes(dns1_selected.get("output_hashes", {}), dns1_source_rel)
        dns1_selection_name = "dns1_primary"
        dns1_reason = "accepted candidate proxy beats baseline comparator"
        dns1_variant = dns1_selected_variant
        dns1_metrics = dns1_candidate.get("metrics", {})
        dns1_proxy_score = dns1_selected_proxy_score
    else:
        baseline_proxy = dns1_manifest.get("baseline_proxy", {})
        dns1_source_rel = str(baseline_proxy["label_path"])
        dns1_expected_sha = expected_sha_from_hashes(baseline_proxy.get("output_hashes", {}), dns1_source_rel)
        dns1_selection_name = "dns1_baseline"
        dns1_reason = "dns1 primary did not satisfy the deterministic proxy improvement rule"
        dns1_variant = str(baseline_proxy.get("variant"))
        dns1_metrics = baseline_proxy.get("metrics", {})
        dns1_proxy_score = float(baseline_proxy.get("proxy_score", 0.0))
    dns1_source = existing_source_with_hash([dns1_source_rel], dns1_expected_sha, "dns1 final selection")

    frozen_sha = str(dns2_freeze.get("baseline_metrics", {}).get("sha256"))
    if frozen_sha != "f12ddfbc1296d6876cfaed019227fbb708edd11f3638cbe100f7ba73b02d9c1c":
        raise ValueError(f"Unexpected dns2 frozen hash in evidence: {frozen_sha}")
    dns2_source = existing_source_with_hash(
        [str(dns2_freeze.get("selected_source", "results/dns2/label.csv")), str(dns2_freeze.get("baseline_source", "results/dns2/label.csv"))],
        frozen_sha,
        "dns2 frozen baseline",
    )

    dns3_selection = dns3_manifest.get("selection", {})
    dns3_primary = dns3_selection.get("primary", {})
    dns3_primary_variant = str(dns3_primary.get("variant"))
    dns3_primary_candidate = find_variant_candidate(dns3_manifest, dns3_primary_variant)
    dns3_primary_gate = dns3_primary_candidate.get("gate", {})
    dns3_baseline_proxy = dns3_manifest.get("baseline_proxy", {})
    dns3_baseline_proxy_score = float(dns3_baseline_proxy.get("proxy_score", 0.0))
    dns3_primary_proxy_score = float(dns3_primary.get("proxy_score", 0.0))
    dns3_use_primary = bool(
        dns3_primary_gate.get("accepted")
        and not dns3_manifest.get("NO_DNS3_IMPROVEMENT", False)
        and dns3_primary_proxy_score > dns3_baseline_proxy_score
    )
    if dns3_use_primary:
        dns3_source_rel = str(dns3_primary["dns3_label_path"])
        dns3_expected_sha = expected_sha_from_hashes(dns3_primary.get("output_hashes", {}), dns3_source_rel)
        dns3_selection_name = "dns3_primary"
        dns3_reason = "primary candidate passed gates and beat baseline proxy"
        dns3_variant = dns3_primary_variant
        dns3_selected_metrics = dns3_primary_candidate.get("metrics", {})
        dns3_proxy_score = dns3_primary_proxy_score
    else:
        dns3_source_rel = str(dns3_baseline_proxy.get("source", "results/dns3/label.csv"))
        dns3_expected_sha = expected_sha_from_hashes(dns3_manifest.get("baseline_result_hashes", {}), "results/dns3/label.csv")
        dns3_selection_name = "dns3_baseline"
        dns3_reason = "baseline proxy is greater than or equal to primary proxy, or NO_DNS3_IMPROVEMENT=true"
        dns3_variant = "baseline"
        dns3_selected_metrics = dns3_baseline_proxy
        dns3_proxy_score = dns3_baseline_proxy_score
    dns3_source = existing_source_with_hash(
        [dns3_source_rel, "results_candidate/dns3_grid/dns3_fallback/dns3/label.csv", "results_candidate/dns3_grid/candidates/kmeans_scaled_k3/dns3/label.csv"],
        dns3_expected_sha,
        "dns3 final selection",
    )

    result_paths = {
        "dns1": solver.RESULTS_DIR / "dns1" / "label.csv",
        "dns2": solver.RESULTS_DIR / "dns2" / "label.csv",
        "dns3": solver.RESULTS_DIR / "dns3" / "label.csv",
    }
    selected_sources = {"dns1": dns1_source, "dns2": dns2_source, "dns3": dns3_source}
    results_hashes: dict[str, dict[str, int | str]] = {}
    for task_name in ["dns1", "dns2", "dns3"]:
        results_hashes[project_relative(result_paths[task_name])] = copy_label_if_needed(selected_sources[task_name], result_paths[task_name])

    answers_dir = solver.PROJECT_ROOT / "submission" / "answers"
    answers_dir.mkdir(parents=True, exist_ok=True)
    expected_answer_names = {"dns1.csv", "dns2.csv", "dns3.csv"}
    for child in list(answers_dir.iterdir()):
        if child.name not in expected_answer_names:
            if child.is_dir():
                shutil.rmtree(child)
            else:
                child.unlink()
    answers_hashes: dict[str, dict[str, int | str]] = {}
    for task_name in ["dns1", "dns2", "dns3"]:
        answer_path = answers_dir / f"{task_name}.csv"
        answers_hashes[project_relative(answer_path)] = copy_label_if_needed(result_paths[task_name], answer_path)

    answers_files = sorted(child.name for child in answers_dir.iterdir())
    label2_files_in_answers = [name for name in answers_files if "label2" in name or name.endswith(".numbers")]

    final_validation_path = EVIDENCE_DIR / "task-7-final-validation.json"
    submission_validation_path = EVIDENCE_DIR / "task-7-submission-validation.json"
    final_payload: dict[str, Any] = {
        "ok": True,
        "task": "task_7_final_selection",
        "run_id": args.run_id,
        "selection_rule": {
            "dns2": "baseline unless Task 6 explicitly selected otherwise",
            "dns3": "dns3_primary if it passes all gates and beats baseline proxy; else baseline dns3",
            "dns1": "dns1_primary if it passes all gates and beats baseline proxy; else baseline dns1",
        },
        "inputs": {
            "dns1_selection": project_relative(dns1_manifest_path),
            "dns2_freeze": project_relative(dns2_freeze_path),
            "dns3_selection": project_relative(dns3_manifest_path),
        },
        "decisions": {
            "dns1": {
                "selection_name": dns1_selection_name,
                "variant": dns1_variant,
                "run_id": dns1_manifest.get("run_id"),
                "source": project_relative(dns1_source),
                "destination": project_relative(result_paths["dns1"]),
                "answers_path": project_relative(answers_dir / "dns1.csv"),
                "reason": dns1_reason,
                "gate_accepted": bool(dns1_candidate_gate.get("accepted")),
                "proxy_score": dns1_proxy_score,
                "baseline_proxy_score": dns1_baseline_proxy_score,
                "metrics": dns1_metrics,
                "sha256": results_hashes["results/dns1/label.csv"]["sha256"],
            },
            "dns2": {
                "selection_name": "dns2_baseline",
                "variant": "baseline_frozen",
                "run_id": dns2_freeze.get("task"),
                "source": project_relative(dns2_source),
                "destination": project_relative(result_paths["dns2"]),
                "answers_path": project_relative(answers_dir / "dns2.csv"),
                "reason": "Task 6 selected baseline freeze and no explicit no-regression variant exists",
                "row_count": dns2_freeze.get("baseline_metrics", {}).get("row_count"),
                "label_counts": dns2_freeze.get("baseline_metrics", {}).get("label_counts"),
                "positive_rate": dns2_freeze.get("baseline_metrics", {}).get("positive_rate"),
                "sha256": results_hashes["results/dns2/label.csv"]["sha256"],
            },
            "dns3": {
                "selection_name": dns3_selection_name,
                "variant": dns3_variant,
                "run_id": dns3_manifest.get("run_id"),
                "source": project_relative(dns3_source),
                "destination": project_relative(result_paths["dns3"]),
                "answers_path": project_relative(answers_dir / "dns3.csv"),
                "reason": dns3_reason,
                "primary_variant": dns3_primary_variant,
                "primary_gate_accepted": bool(dns3_primary_gate.get("accepted")),
                "primary_proxy": {
                    "proxy_score": dns3_primary_proxy_score,
                    "metrics": dns3_primary_candidate.get("metrics", {}),
                },
                "baseline_proxy": dns3_baseline_proxy,
                "proxy_score": dns3_proxy_score,
                "selected_label_counts": dns3_selected_metrics.get("label_counts"),
                "NO_DNS3_IMPROVEMENT": bool(dns3_manifest.get("NO_DNS3_IMPROVEMENT")),
                "sha256": results_hashes["results/dns3/label.csv"]["sha256"],
            },
        },
        "output_hashes": {
            "results": results_hashes,
            "submission_answers": answers_hashes,
        },
        "packaging": {
            "answers_dir": project_relative(answers_dir),
            "answers_files": answers_files,
            "expected_answers_files": sorted(expected_answer_names),
            "label2_or_numbers_files_in_answers": label2_files_in_answers,
            "label2_excluded": not label2_files_in_answers,
        },
        "validation_status": {
            "results": validation_status(final_validation_path),
            "submission_answers": validation_status(submission_validation_path),
        },
    }
    write_task7_run_summary(final_payload)
    final_payload["run_summary"] = {
        "path": project_relative(solver.REPORTS_DIR / "run_summary.md"),
        "hash": hash_file(solver.REPORTS_DIR / "run_summary.md"),
    }
    write_json(EVIDENCE_DIR / "final_selection.json", final_payload)
    return final_payload


def _sorted_cluster_items(clusters: dict[str, Any]) -> list[tuple[str, dict[str, Any]]]:
    def cluster_key(item: tuple[str, Any]) -> tuple[int, str]:
        label = str(item[0])
        return (_safe_int(label, 10**9), label)

    return [(str(label), dict(cluster)) for label, cluster in sorted(clusters.items(), key=cluster_key)]


def dns3_interpretable_candidate_thresholds(candidate: dict[str, Any]) -> dict[str, Any]:
    for container in [candidate, candidate.get("gate", {}), candidate.get("metrics", {})]:
        if isinstance(container, dict) and isinstance(container.get("thresholds"), dict):
            return dict(container["thresholds"])
    integrity = candidate.get("label_integrity") or candidate.get("metrics", {}).get("label_integrity") or {}
    row_count = _safe_int(integrity.get("row_count") or integrity.get("expected_row_count"), 0)
    return dns3_interpretable_thresholds(row_count)


def dns3_interpretable_profile_summary(candidate: dict[str, Any]) -> dict[str, Any]:
    profile_gate = candidate.get("profile_gate") or candidate.get("metrics", {}).get("profile_gate") or {}
    clusters = profile_gate.get("clusters") if isinstance(profile_gate, dict) else {}
    if not isinstance(clusters, dict):
        clusters = {}
    per_cluster: dict[str, Any] = {}
    passing_metric_counts: list[int] = []
    failed_reasons: list[str] = []

    if not clusters:
        failed_reasons.append("profile_gate_missing_clusters")

    for label, cluster in _sorted_cluster_items(clusters):
        raw_evidence_metrics = cluster.get("evidence_metrics")
        evidence_metrics: list[Any] = raw_evidence_metrics if isinstance(raw_evidence_metrics, list) else []
        passing_evidence_count = sum(1 for metric in evidence_metrics if isinstance(metric, dict) and metric.get("passes") is True)
        passing_metric_count = _safe_int(cluster.get("passing_metric_count"), passing_evidence_count)
        cluster_passed = bool(cluster.get("passed"))
        passing_metric_counts.append(passing_metric_count)
        per_cluster[label] = {
            "passed": cluster_passed,
            "cluster_size": _safe_int(cluster.get("cluster_size"), 0),
            "passing_metric_count": passing_metric_count,
            "passing_evidence_metric_count": passing_evidence_count,
            "eligible_metric_count": _safe_int(cluster.get("eligible_metric_count"), 0),
        }
        if not cluster_passed:
            failed_reasons.append(f"profile_cluster_{label}_failed")
        if passing_metric_count < 2:
            failed_reasons.append(f"profile_cluster_{label}_passing_metric_count<2")
        if passing_evidence_count < 2:
            failed_reasons.append(f"profile_cluster_{label}_passing_evidence_metric_count<2")

    top_level_passed = bool(profile_gate.get("passed") or profile_gate.get("accepted")) if isinstance(profile_gate, dict) else False
    if not top_level_passed:
        failed_reasons.append("profile_gate_failed")
    return {
        "formula": DNS3_INTERPRETABLE_PROFILE_SCORE_FORMULA,
        "passed": top_level_passed and not failed_reasons,
        "worst_cluster_profile_score": min(passing_metric_counts) if passing_metric_counts else 0,
        "per_cluster": per_cluster,
        "failed_reasons": _unique_reasons(failed_reasons),
        "all_clusters_passed": all(item["passed"] for item in per_cluster.values()) if per_cluster else False,
        "all_clusters_have_two_evidence_metrics": all(
            item["passing_evidence_metric_count"] >= 2 and item["passing_metric_count"] >= 2
            for item in per_cluster.values()
        )
        if per_cluster
        else False,
    }


def dns3_interpretable_ordering_inputs(candidate: dict[str, Any], profile_summary: dict[str, Any]) -> dict[str, Any]:
    route = str(candidate.get("route"))
    algorithm = str(candidate.get("algorithm"))
    median_nmi = _safe_float(candidate.get("median_pairwise_nmi"), -1.0)
    median_ari = _safe_float(candidate.get("median_pairwise_ari"), -1.0)
    return {
        "k": _safe_int(candidate.get("k"), 0),
        "cluster_count": _safe_int(candidate.get("cluster_count"), 0),
        "worst_cluster_profile_score": _safe_int(profile_summary.get("worst_cluster_profile_score"), 0),
        "median_pairwise_nmi": median_nmi,
        "median_pairwise_ari": median_ari,
        "route": route,
        "route_order": DNS3_INTERPRETABLE_ROUTE_ORDER.get(route, 99),
        "algorithm": algorithm,
        "algorithm_order": DNS3_INTERPRETABLE_ALGORITHM_ORDER.get(algorithm, 99),
        "variant": str(candidate.get("variant")),
    }


def dns3_interpretable_selection_sort_key(evaluation: dict[str, Any]) -> tuple[int, int, float, float, int, int, str]:
    inputs = evaluation["ordering_inputs"]
    return (
        int(inputs["k"]),
        -int(inputs["worst_cluster_profile_score"]),
        -float(inputs["median_pairwise_nmi"]),
        -float(inputs["median_pairwise_ari"]),
        int(inputs["route_order"]),
        int(inputs["algorithm_order"]),
        str(inputs["variant"]),
    )


def evaluate_dns3_interpretable_selection_candidate(candidate: dict[str, Any]) -> dict[str, Any]:
    reasons: list[str] = []
    variant = str(candidate.get("variant"))
    route = str(candidate.get("route"))
    algorithm = str(candidate.get("algorithm"))
    thresholds = dns3_interpretable_candidate_thresholds(candidate)
    profile_summary = dns3_interpretable_profile_summary(candidate)
    ordering_inputs = dns3_interpretable_ordering_inputs(candidate, profile_summary)

    if route not in DNS3_INTERPRETABLE_ROUTE_ORDER:
        reasons.append("route_not_in_allowed_order")
    if algorithm not in DNS3_INTERPRETABLE_ALGORITHM_ORDER:
        reasons.append("algorithm_not_in_allowed_order")

    label_path_text = str(candidate.get("label_path") or "")
    observed_label_hash: dict[str, int | str] | None = None
    expected_hashes = {
        str(value)
        for value in [
            candidate.get("label_sha256"),
            candidate.get("hash"),
            candidate.get("label_hash", {}).get("sha256") if isinstance(candidate.get("label_hash"), dict) else None,
            candidate.get("metrics", {}).get("label_sha256") if isinstance(candidate.get("metrics"), dict) else None,
        ]
        if value
    }
    if not label_path_text:
        reasons.append("label_path_missing")
    else:
        label_path = project_path(label_path_text)
        if not label_path.exists():
            reasons.append("label_file_missing")
        else:
            observed_hash = hash_file(label_path)
            observed_label_hash = observed_hash
            if expected_hashes and str(observed_hash["sha256"]) not in expected_hashes:
                reasons.append("label_sha256_mismatch")

    integrity = candidate.get("label_integrity") or candidate.get("metrics", {}).get("label_integrity") or {}
    if integrity.get("columns") != ["fqdn_no", "label"]:
        reasons.append("output_columns_invalid")
    if not integrity.get("fqdn_set_matches_expected"):
        reasons.append("fqdn_rows_do_not_match_expected_dns3_question_fqdn")
    if _safe_int(integrity.get("row_count"), 0) != _safe_int(integrity.get("expected_row_count"), -1):
        reasons.append("output_row_count_mismatch")
    if _safe_int(integrity.get("duplicate_fqdn_count"), 0) > 0:
        reasons.append("duplicate_fqdn_count>0")
    if _safe_int(integrity.get("missing_fqdn_count"), 0) > 0:
        reasons.append("missing_fqdn_count>0")
    if _safe_int(integrity.get("extra_fqdn_count"), 0) > 0:
        reasons.append("extra_fqdn_count>0")
    if _safe_int(candidate.get("invalid_label_count"), 0) > 0:
        reasons.append("invalid_label_count>0")
    if _safe_int(candidate.get("negative_label_count"), 0) > 0:
        reasons.append("negative_label_count>0")

    cluster_count = _safe_int(candidate.get("cluster_count"), 0)
    if cluster_count < 3:
        reasons.append("cluster_count<3")
    if cluster_count >= 12:
        reasons.append("cluster_count>=12")
    if cluster_count < _safe_int(thresholds.get("cluster_count_min"), 3) or cluster_count > _safe_int(thresholds.get("cluster_count_max"), 8):
        reasons.append("cluster_count_outside_3_to_8")
    if _safe_int(candidate.get("min_cluster_size"), 0) < _safe_int(thresholds.get("min_cluster_size"), 350):
        reasons.append(f"min_cluster_size<{_safe_int(thresholds.get('min_cluster_size'), 350)}")
    if _safe_float(candidate.get("max_cluster_fraction"), 1.0) > _safe_float(thresholds.get("max_cluster_fraction"), DNS3_INTERPRETABLE_MAX_CLUSTER_FRACTION):
        reasons.append("max_cluster_fraction>0.55")

    median_nmi = candidate.get("median_pairwise_nmi")
    if median_nmi is None or _safe_float(median_nmi, -1.0) < _safe_float(thresholds.get("min_median_pairwise_nmi"), DNS3_INTERPRETABLE_MIN_NMI):
        reasons.append("median_pairwise_nmi<0.80")
    median_ari = candidate.get("median_pairwise_ari")
    if median_ari is None or _safe_float(median_ari, -1.0) < _safe_float(thresholds.get("min_median_pairwise_ari"), DNS3_INTERPRETABLE_MIN_ARI):
        reasons.append("median_pairwise_ari<0.60")
    separation_ratio = candidate.get("centroid_separation_ratio")
    if separation_ratio is None or _safe_float(separation_ratio, -1.0) < _safe_float(thresholds.get("min_centroid_separation_ratio"), DNS3_INTERPRETABLE_MIN_SEPARATION_RATIO):
        reasons.append("centroid_separation_ratio<0.25")
    sample_silhouette = candidate.get("sample_silhouette", candidate.get("silhouette"))
    if sample_silhouette is None or _safe_float(sample_silhouette, -1.0) <= 0.0:
        reasons.append("sample_silhouette<=0")
    if not profile_summary["passed"]:
        reasons.extend(str(reason) for reason in profile_summary["failed_reasons"])

    registry_accepted = bool(candidate.get("accepted") or candidate.get("gate", {}).get("accepted"))
    if not registry_accepted and not reasons:
        reasons.append("registry_candidate_not_accepted")

    rejection_reasons = _unique_reasons(reasons)
    return {
        "variant": variant,
        "accepted": not rejection_reasons,
        "rejection_reasons": rejection_reasons,
        "primary_rejection_reason": rejection_reasons[0] if rejection_reasons else None,
        "ordering_inputs": ordering_inputs,
        "profile_summary": profile_summary,
        "candidate": candidate,
        "observed_label_hash": observed_label_hash,
        "thresholds": thresholds,
    }


def summarize_dns3_interpretable_evaluation(evaluation: dict[str, Any]) -> dict[str, Any]:
    candidate = evaluation["candidate"]
    return {
        "variant": evaluation["variant"],
        "accepted": bool(evaluation["accepted"]),
        "rejection_reasons": evaluation["rejection_reasons"],
        "primary_rejection_reason": evaluation["primary_rejection_reason"],
        "ordering_inputs": evaluation["ordering_inputs"],
        "profile_summary": evaluation["profile_summary"],
        "route": candidate.get("route"),
        "algorithm": candidate.get("algorithm"),
        "k": candidate.get("k"),
        "cluster_count": candidate.get("cluster_count"),
        "label_path": candidate.get("label_path"),
        "label_sha256": candidate.get("label_sha256"),
        "min_cluster_size": candidate.get("min_cluster_size"),
        "max_cluster_fraction": candidate.get("max_cluster_fraction"),
        "sample_silhouette": candidate.get("sample_silhouette"),
        "centroid_separation_ratio": candidate.get("centroid_separation_ratio"),
        "median_pairwise_nmi": candidate.get("median_pairwise_nmi"),
        "median_pairwise_ari": candidate.get("median_pairwise_ari"),
    }


def dns3_interpretable_rejection_summary(evaluations: list[dict[str, Any]]) -> dict[str, Any]:
    by_reason: Counter[str] = Counter()
    by_primary_reason: Counter[str] = Counter()
    rejected_count = 0
    for evaluation in evaluations:
        if evaluation["accepted"]:
            continue
        rejected_count += 1
        primary = evaluation.get("primary_rejection_reason")
        if primary:
            by_primary_reason[str(primary)] += 1
        for reason in evaluation.get("rejection_reasons", []):
            by_reason[str(reason)] += 1
    return {
        "rejected_candidate_count": rejected_count,
        "accepted_candidate_count": len(evaluations) - rejected_count,
        "by_reason": dict(sorted(by_reason.items())),
        "by_primary_reason": dict(sorted(by_primary_reason.items())),
    }


def dns3_interpretable_output_hashes() -> dict[str, dict[str, int | str]]:
    paths = [
        solver.RESULTS_DIR / "dns1" / "label.csv",
        solver.RESULTS_DIR / "dns2" / "label.csv",
        solver.RESULTS_DIR / "dns3" / "label.csv",
        solver.PROJECT_ROOT / "submission" / "answers" / "dns1.csv",
        solver.PROJECT_ROOT / "submission" / "answers" / "dns2.csv",
        solver.PROJECT_ROOT / "submission" / "answers" / "dns3.csv",
    ]
    return {project_relative(path): hash_file(path) for path in paths}


def assert_dns1_dns2_locked(hashes: dict[str, dict[str, int | str]], context: str) -> None:
    expected = {
        "results/dns1/label.csv": DNS1_LOCKED_SHA256,
        "results/dns2/label.csv": DNS2_LOCKED_SHA256,
        "submission/answers/dns1.csv": DNS1_LOCKED_SHA256,
        "submission/answers/dns2.csv": DNS2_LOCKED_SHA256,
    }
    mismatches = [f"{path}={hashes.get(path, {}).get('sha256')}" for path, sha in expected.items() if hashes.get(path, {}).get("sha256") != sha]
    if mismatches:
        raise ValueError(f"dns1/dns2 locked hash mismatch {context}: {mismatches}")


def run_task4_validator(results_path: str, *, answers_layout: bool) -> dict[str, Any]:
    command = [sys.executable, "scripts/validate_outputs.py", "--results", results_path, "--data", "data"]
    if answers_layout:
        command.append("--answers-layout")
    completed = subprocess.run(
        command,
        cwd=solver.PROJECT_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    parsed: dict[str, Any] | None = None
    if completed.stdout.strip():
        try:
            parsed = json.loads(completed.stdout)
        except json.JSONDecodeError:
            parsed = None
    return {
        "command": " ".join(command),
        "cwd": str(solver.PROJECT_ROOT),
        "exit_code": completed.returncode,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
        "parsed_stdout": parsed,
        "ok": completed.returncode == 0 and bool(parsed and parsed.get("ok")),
    }


def csv_row_header_check(path: Path) -> dict[str, Any]:
    fieldnames, rows = read_label_csv(path)
    return {
        "path": project_relative(path),
        "columns": fieldnames,
        "row_count": len(rows),
        "unique_fqdn": len({str(row.get("fqdn_no", "")).strip() for row in rows}),
        "hash": hash_file(path),
    }


def dns3_task4_integrity_checks(path: Path) -> dict[str, Any]:
    expected_fqdn_fields, expected_fqdn_rows = read_label_csv(solver.DATA_DIR / "dns3" / "question" / "fqdn.csv")
    if "fqdn_no" not in expected_fqdn_fields:
        raise ValueError("dns3 fqdn reference is missing fqdn_no")
    expected_fqdn = [str(row.get("fqdn_no", "")).strip() for row in expected_fqdn_rows]
    diagnostics = dns3_label_diagnostics(path, seed_set=DNS3_INTERPRETABLE_SEED_SET)
    integrity = dns3_interpretable_label_integrity(path, expected_fqdn)
    return {
        "path": project_relative(path),
        "columns": diagnostics.get("columns"),
        "row_count": diagnostics.get("rows"),
        "expected_row_count": len(expected_fqdn),
        "nonnegative_integer_labels": diagnostics.get("invalid_label_count") == 0 and diagnostics.get("negative_label_count") == 0,
        "unique_cluster_count": diagnostics.get("cluster_count"),
        "label_counts": diagnostics.get("label_counts"),
        "fqdn_set_matches_expected": integrity.get("fqdn_set_matches_expected"),
        "integrity": integrity,
        "hash": hash_file(path),
    }


def build_dns3_task4_package_validation(
    *,
    before_hashes: dict[str, dict[str, int | str]],
    after_hashes: dict[str, dict[str, int | str]],
    final_selection_path: Path,
    selection_check_path: Path,
    selected: bool,
) -> dict[str, Any]:
    results_validation = run_task4_validator("results", answers_layout=False)
    submission_validation = run_task4_validator("submission/answers", answers_layout=True)
    answers_dir = solver.PROJECT_ROOT / "submission" / "answers"
    answer_files = sorted(child.name for child in answers_dir.iterdir() if child.is_file())
    expected_answer_files = ["dns1.csv", "dns2.csv", "dns3.csv"]
    row_header_checks = {
        "results/dns1/label.csv": csv_row_header_check(solver.RESULTS_DIR / "dns1" / "label.csv"),
        "results/dns2/label.csv": csv_row_header_check(solver.RESULTS_DIR / "dns2" / "label.csv"),
        "results/dns3/label.csv": csv_row_header_check(solver.RESULTS_DIR / "dns3" / "label.csv"),
        "submission/answers/dns1.csv": csv_row_header_check(answers_dir / "dns1.csv"),
        "submission/answers/dns2.csv": csv_row_header_check(answers_dir / "dns2.csv"),
        "submission/answers/dns3.csv": csv_row_header_check(answers_dir / "dns3.csv"),
    }
    dns3_checks = {
        "results/dns3/label.csv": dns3_task4_integrity_checks(solver.RESULTS_DIR / "dns3" / "label.csv"),
        "submission/answers/dns3.csv": dns3_task4_integrity_checks(answers_dir / "dns3.csv"),
    }
    dns1_dns2_locked = all(
        after_hashes.get(path, {}).get("sha256") == expected
        for path, expected in {
            "results/dns1/label.csv": DNS1_LOCKED_SHA256,
            "results/dns2/label.csv": DNS2_LOCKED_SHA256,
            "submission/answers/dns1.csv": DNS1_LOCKED_SHA256,
            "submission/answers/dns2.csv": DNS2_LOCKED_SHA256,
        }.items()
    )
    dns3_hash_ok = bool(after_hashes.get("results/dns3/label.csv", {}).get("sha256")) and after_hashes.get(
        "results/dns3/label.csv", {}
    ).get("sha256") == after_hashes.get("submission/answers/dns3.csv", {}).get("sha256")
    if not selected:
        dns3_hash_ok = dns3_hash_ok and after_hashes.get("results/dns3/label.csv", {}).get("sha256") == DNS3_INTERPRETABLE_FALLBACK_SHA256
    row_header_ok = all(check["columns"] in (["fqdn_no", "label"], ["fqdn_no", "family_no"]) for check in row_header_checks.values())
    dns3_integrity_ok = all(
        check["row_count"] == 17468
        and check["expected_row_count"] == 17468
        and check["nonnegative_integer_labels"]
        and check["fqdn_set_matches_expected"]
        for check in dns3_checks.values()
    )
    ok = bool(
        results_validation["ok"]
        and submission_validation["ok"]
        and answer_files == expected_answer_files
        and dns1_dns2_locked
        and dns3_hash_ok
        and row_header_ok
        and dns3_integrity_ok
    )
    return {
        "ok": ok,
        "task": "task_4_dns3_interpretable_package_validation",
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "local_only": True,
        "gitee_pushed": False,
        "selected_candidate_staged": selected,
        "final_selection_json": project_relative(final_selection_path),
        "selection_check_json": project_relative(selection_check_path),
        "validators": {
            "results": results_validation,
            "submission_answers": submission_validation,
        },
        "hashes": {
            "before": before_hashes,
            "after": after_hashes,
            "dns1_dns2_locked": dns1_dns2_locked,
            "dns3_result_submission_match": dns3_hash_ok,
        },
        "answers_files": answer_files,
        "expected_answers_files": expected_answer_files,
        "answers_files_exact": answer_files == expected_answer_files,
        "row_header_checks": row_header_checks,
        "dns3_integrity_checks": dns3_checks,
        "checks": {
            "validators_ok": results_validation["ok"] and submission_validation["ok"],
            "answer_files_exact": answer_files == expected_answer_files,
            "dns1_dns2_locked": dns1_dns2_locked,
            "dns3_hash_ok": dns3_hash_ok,
            "row_header_ok": row_header_ok,
            "dns3_integrity_ok": dns3_integrity_ok,
        },
    }


def nested_key_exists(value: Any, key: str) -> bool:
    if isinstance(value, dict):
        return any(item_key == key or nested_key_exists(item_value, key) for item_key, item_value in value.items())
    if isinstance(value, list):
        return any(nested_key_exists(item, key) for item in value)
    return False


def build_dns3_interpretable_selection_payload(
    *,
    args: argparse.Namespace,
    registry: dict[str, Any],
    evaluations: list[dict[str, Any]],
    selected_evaluation: dict[str, Any] | None,
    before_hashes: dict[str, dict[str, int | str]],
    after_hashes: dict[str, dict[str, int | str]],
) -> dict[str, Any]:
    accepted_evaluations = sorted([item for item in evaluations if item["accepted"]], key=dns3_interpretable_selection_sort_key)
    selected_candidate = summarize_dns3_interpretable_evaluation(selected_evaluation) if selected_evaluation is not None else None
    return {
        "ok": True,
        "task": "task_4_select_smallest_valid_local_dns3_candidate",
        "mode": args.mode,
        "run_id": args.run_id,
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "local_only": True,
        "gitee_pushed": False,
        "source_registry": project_relative(DNS3_INTERPRETABLE_EVIDENCE_DIR / "candidate_registry.json"),
        "candidate_count": len(evaluations),
        "registry_candidate_count": registry.get("candidate_count"),
        "selection_rule": {
            "source_of_truth": "candidate_registry.json",
            "reject_if": [
                "candidate label artifact missing or sha256 differs from registry",
                "output validation fails for columns, nonnegative integer labels, row count, duplicate/missing/extra fqdn, or fqdn set",
                "cluster_count < 3 or cluster_count >= 12",
                "cluster_count outside registry size gate 3..8",
                "min_cluster_size below registry threshold",
                "max_cluster_fraction above registry threshold",
                "median_pairwise_nmi < 0.80",
                "median_pairwise_ari < 0.60",
                "centroid_separation_ratio < 0.25",
                "sample_silhouette <= 0",
                "any cluster profile gate fails or has fewer than two passing evidence metrics",
            ],
            "choose": [
                "smallest k",
                "highest worst-cluster profile score",
                "highest median_pairwise_nmi",
                "highest median_pairwise_ari",
                "route order traffic_only, traffic_plus_ip, traffic_plus_lexical",
                "algorithm order MiniBatchKMeans, KMeans, GaussianMixture",
                "lexicographic variant",
            ],
            "profile_score_formula": DNS3_INTERPRETABLE_PROFILE_SCORE_FORMULA,
        },
        "NO_INTERPRETABLE_DNS3_CANDIDATE": selected_evaluation is None,
        "selected_candidate": selected_candidate,
        "selected_ordering_inputs": selected_evaluation["ordering_inputs"] if selected_evaluation is not None else None,
        "passed_candidate_count": len(accepted_evaluations),
        "passed_candidates_in_selection_order": [summarize_dns3_interpretable_evaluation(item) for item in accepted_evaluations],
        "rejection_summary": dns3_interpretable_rejection_summary(evaluations),
        "candidate_evaluations": [summarize_dns3_interpretable_evaluation(item) for item in evaluations],
        "output_hashes": {
            "before": before_hashes,
            "after": after_hashes,
        },
    }


def run_dns3_interpretable_finalize(args: argparse.Namespace) -> dict[str, Any]:
    if args.task != "dns3":
        raise ValueError("dns3-interpretable Task 4 finalize must be run with --task dns3")
    registry_path = DNS3_INTERPRETABLE_EVIDENCE_DIR / "candidate_registry.json"
    registry = read_json(registry_path)
    candidates = list(registry.get("candidates", []))
    before_hashes = dns3_interpretable_output_hashes()
    assert_dns1_dns2_locked(before_hashes, "before dns3 interpretable finalize")

    evaluations = [evaluate_dns3_interpretable_selection_candidate(candidate) for candidate in candidates]
    accepted_evaluations = sorted([item for item in evaluations if item["accepted"]], key=dns3_interpretable_selection_sort_key)
    selected_evaluation = accepted_evaluations[0] if accepted_evaluations else None

    if selected_evaluation is None:
        current_dns3_hash = before_hashes.get("results/dns3/label.csv", {}).get("sha256")
        current_submission_dns3_hash = before_hashes.get("submission/answers/dns3.csv", {}).get("sha256")
        if current_dns3_hash != DNS3_INTERPRETABLE_FALLBACK_SHA256 or current_submission_dns3_hash != DNS3_INTERPRETABLE_FALLBACK_SHA256:
            raise ValueError(
                "No interpretable dns3 candidate passed, but current dns3 does not match the required fallback hash"
            )
    else:
        selected_candidate = selected_evaluation["candidate"]
        expected_sha = str(selected_candidate.get("label_sha256") or selected_candidate.get("hash"))
        source = existing_source_with_hash([str(selected_candidate["label_path"])], expected_sha, "dns3 interpretable selected candidate")
        result_destination = solver.RESULTS_DIR / "dns3" / "label.csv"
        answer_destination = solver.PROJECT_ROOT / "submission" / "answers" / "dns3.csv"
        copy_label_if_needed(source, result_destination)
        copy_label_if_needed(result_destination, answer_destination)

    after_hashes = dns3_interpretable_output_hashes()
    assert_dns1_dns2_locked(after_hashes, "after dns3 interpretable finalize")
    if selected_evaluation is not None:
        selected_sha = str(selected_evaluation["candidate"].get("label_sha256") or selected_evaluation["candidate"].get("hash"))
        if after_hashes.get("results/dns3/label.csv", {}).get("sha256") != selected_sha:
            raise ValueError("staged results/dns3 hash does not match selected candidate")
        if after_hashes.get("submission/answers/dns3.csv", {}).get("sha256") != selected_sha:
            raise ValueError("staged submission dns3 hash does not match selected candidate")

    final_selection_path = DNS3_INTERPRETABLE_EVIDENCE_DIR / "final_selection.json"
    selection_check_path = DNS3_INTERPRETABLE_EVIDENCE_DIR / "task-4-selection-check.json"
    package_validation_path = DNS3_INTERPRETABLE_EVIDENCE_DIR / "task-4-package-validation.json"
    final_payload = build_dns3_interpretable_selection_payload(
        args=args,
        registry=registry,
        evaluations=evaluations,
        selected_evaluation=selected_evaluation,
        before_hashes=before_hashes,
        after_hashes=after_hashes,
    )
    write_json(final_selection_path, final_payload)

    selection_check_payload = {
        "ok": True,
        "task": "task_4_dns3_interpretable_selection_check",
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
        "local_only": True,
        "gitee_pushed": False,
        "final_selection_json": project_relative(final_selection_path),
        "selected_candidate": final_payload["selected_candidate"],
        "fallback": bool(final_payload["NO_INTERPRETABLE_DNS3_CANDIDATE"]),
        "selected_ordering_inputs": final_payload["selected_ordering_inputs"],
        "first_pass_candidate_in_order": final_payload["passed_candidates_in_selection_order"][0]
        if final_payload["passed_candidates_in_selection_order"]
        else None,
        "ordering_assertion": (
            final_payload["selected_candidate"] == final_payload["passed_candidates_in_selection_order"][0]
            if final_payload["passed_candidates_in_selection_order"]
            else final_payload["NO_INTERPRETABLE_DNS3_CANDIDATE"]
        ),
        "manual_override_absent": not nested_key_exists(final_payload, "manual_override"),
        "rejection_summary": final_payload["rejection_summary"],
    }
    selection_check_payload["ok"] = bool(
        selection_check_payload["ordering_assertion"] and selection_check_payload["manual_override_absent"]
    )
    write_json(selection_check_path, selection_check_payload)

    package_payload = build_dns3_task4_package_validation(
        before_hashes=before_hashes,
        after_hashes=after_hashes,
        final_selection_path=final_selection_path,
        selection_check_path=selection_check_path,
        selected=selected_evaluation is not None,
    )
    write_json(package_validation_path, package_payload)
    if not selection_check_payload["ok"]:
        raise ValueError("Task 4 selection check failed")
    if not package_payload["ok"]:
        raise ValueError("Task 4 package validation failed")
    return {
        "ok": True,
        "task": "task_4_select_smallest_valid_local_dns3_candidate",
        "selected_candidate": final_payload["selected_candidate"],
        "NO_INTERPRETABLE_DNS3_CANDIDATE": final_payload["NO_INTERPRETABLE_DNS3_CANDIDATE"],
        "final_selection_json": project_relative(final_selection_path),
        "selection_check_json": project_relative(selection_check_path),
        "package_validation_json": project_relative(package_validation_path),
        "output_hashes": after_hashes,
    }


__all__ = [
    "write_task7_run_summary",
    "run_task7_finalize",
    "_sorted_cluster_items",
    "dns3_interpretable_candidate_thresholds",
    "dns3_interpretable_profile_summary",
    "dns3_interpretable_ordering_inputs",
    "dns3_interpretable_selection_sort_key",
    "evaluate_dns3_interpretable_selection_candidate",
    "summarize_dns3_interpretable_evaluation",
    "dns3_interpretable_rejection_summary",
    "dns3_interpretable_output_hashes",
    "assert_dns1_dns2_locked",
    "run_task4_validator",
    "csv_row_header_check",
    "dns3_task4_integrity_checks",
    "build_dns3_task4_package_validation",
    "nested_key_exists",
    "build_dns3_interpretable_selection_payload",
    "run_dns3_interpretable_finalize",
]
